BEGIN;

CREATE TABLE canvas_mcp_alembic_version (
    version_num VARCHAR(32) NOT NULL,
    CONSTRAINT canvas_mcp_alembic_version_pkc PRIMARY KEY (version_num)
);

-- Running upgrade  -> 0001_baseline_v4

CREATE TABLE meta (
    key TEXT NOT NULL,
    value TEXT NOT NULL,
    PRIMARY KEY (key)
);

CREATE TABLE canvas_tokens (
    tenant_id TEXT COLLATE "C" NOT NULL,
    object_id TEXT COLLATE "C" NOT NULL,
    key_id TEXT COLLATE "C" NOT NULL,
    nonce BYTEA NOT NULL,
    ciphertext BYTEA NOT NULL,
    canvas_user_id TEXT NOT NULL,
    canvas_user_name TEXT NOT NULL,
    entra_display_name TEXT DEFAULT '' NOT NULL,
    entra_upn TEXT DEFAULT '' NOT NULL,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    last_used_at BIGINT,
    canvas_host TEXT,
    principal_key TEXT COLLATE "C",
    status TEXT DEFAULT 'active' NOT NULL,
    invalid_reason TEXT,
    invalid_since BIGINT,
    last_verified_at BIGINT,
    expires_hint_at BIGINT,
    PRIMARY KEY (tenant_id, object_id)
);

CREATE UNIQUE INDEX canvas_tokens_principal_key ON canvas_tokens (principal_key);

CREATE TABLE user_tool_prefs (
    principal_key TEXT COLLATE "C" NOT NULL,
    enabled_write_tools TEXT DEFAULT '[]' NOT NULL,
    enabled_at TEXT DEFAULT '{}' NOT NULL,
    updated_at BIGINT NOT NULL,
    updated_via TEXT DEFAULT 'account_web' NOT NULL,
    PRIMARY KEY (principal_key)
);

CREATE TABLE principal_status (
    principal_key TEXT COLLATE "C" NOT NULL,
    status TEXT DEFAULT 'active' NOT NULL,
    disabled_reason TEXT,
    disabled_at BIGINT,
    disabled_by TEXT,
    display_name TEXT DEFAULT '' NOT NULL,
    upn TEXT DEFAULT '' NOT NULL,
    session_epoch BIGINT DEFAULT 0 NOT NULL,
    is_owner BIGINT DEFAULT 0 NOT NULL,
    owner_seen_at BIGINT,
    updated_at BIGINT NOT NULL,
    PRIMARY KEY (principal_key)
);

CREATE TABLE principal_status_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    principal_key TEXT COLLATE "C" NOT NULL,
    action TEXT NOT NULL,
    actor TEXT,
    reason TEXT,
    session_epoch BIGINT NOT NULL,
    at BIGINT NOT NULL,
    PRIMARY KEY (id)
);

CREATE INDEX principal_status_events_principal ON principal_status_events (principal_key, id);

CREATE TABLE credential_generations (
    principal_key TEXT COLLATE "C" NOT NULL,
    generation BIGINT NOT NULL,
    reason TEXT DEFAULT '' NOT NULL,
    updated_at BIGINT NOT NULL,
    PRIMARY KEY (principal_key)
);

INSERT INTO meta (key, value) VALUES ('schema_version', '4');

INSERT INTO canvas_mcp_alembic_version (version_num) VALUES ('0001_baseline_v4') RETURNING canvas_mcp_alembic_version.version_num;

-- Running upgrade 0001_baseline_v4 -> 0002_accounts

DO $$ BEGIN IF EXISTS (SELECT 1 FROM canvas_tokens) OR EXISTS (SELECT 1 FROM principal_status) OR EXISTS (SELECT 1 FROM user_tool_prefs) OR EXISTS (SELECT 1 FROM credential_generations) OR EXISTS (SELECT 1 FROM principal_status_events) THEN RAISE EXCEPTION 'this database holds data; upgrade it online (token_admin db upgrade)'; END IF; END $$;

CREATE TABLE accounts (
    id TEXT COLLATE "C" NOT NULL,
    status TEXT DEFAULT 'active' NOT NULL,
    role TEXT DEFAULT 'user' NOT NULL,
    role_source TEXT,
    role_seen_at BIGINT,
    admitted_via TEXT NOT NULL,
    display_name TEXT DEFAULT '' NOT NULL,
    contact_email TEXT,
    ui_locale TEXT,
    created_at BIGINT NOT NULL,
    approved_at BIGINT,
    approved_by TEXT COLLATE "C",
    disabled_reason TEXT,
    disabled_at BIGINT,
    disabled_by TEXT COLLATE "C",
    last_login_at BIGINT,
    session_epoch BIGINT DEFAULT 0 NOT NULL,
    updated_at BIGINT NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT accounts_status_check CHECK (status IN ('pending', 'active', 'disabled')),
    CONSTRAINT accounts_role_check CHECK (role IN ('user', 'owner'))
);

CREATE INDEX accounts_status_role ON accounts (status, role);

CREATE TABLE external_identities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    account_id TEXT COLLATE "C" NOT NULL,
    provider_id TEXT COLLATE "C" NOT NULL,
    issuer TEXT COLLATE "C" NOT NULL,
    subject TEXT COLLATE "C" NOT NULL,
    username TEXT,
    email TEXT,
    email_verified BIGINT DEFAULT 0 NOT NULL,
    linked_at BIGINT NOT NULL,
    last_login_at BIGINT,
    PRIMARY KEY (id),
    CONSTRAINT external_identities_key UNIQUE (provider_id, issuer, subject)
);

CREATE INDEX external_identities_account ON external_identities (account_id);

CREATE TABLE auth_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    at BIGINT NOT NULL,
    account_id TEXT COLLATE "C",
    provider_id TEXT NOT NULL,
    surface TEXT NOT NULL,
    outcome TEXT NOT NULL,
    reason TEXT NOT NULL,
    ip TEXT DEFAULT 'unknown' NOT NULL,
    ua_hash TEXT,
    PRIMARY KEY (id)
);

CREATE INDEX auth_events_account ON auth_events (account_id, id);

CREATE INDEX auth_events_at ON auth_events (at);

CREATE TABLE audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    at BIGINT NOT NULL,
    actor TEXT COLLATE "C" NOT NULL,
    action TEXT NOT NULL,
    target TEXT COLLATE "C",
    reason TEXT,
    detail TEXT DEFAULT '{}' NOT NULL,
    PRIMARY KEY (id)
);

CREATE INDEX audit_log_target ON audit_log (target, id);

DROP INDEX canvas_tokens_principal_key;

DROP TABLE canvas_tokens;

CREATE TABLE canvas_tokens (
    principal_key TEXT COLLATE "C" NOT NULL,
    key_id TEXT COLLATE "C" NOT NULL,
    nonce BYTEA NOT NULL,
    ciphertext BYTEA NOT NULL,
    canvas_user_id TEXT NOT NULL,
    canvas_user_name TEXT NOT NULL,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    last_used_at BIGINT,
    canvas_host TEXT,
    status TEXT DEFAULT 'active' NOT NULL,
    invalid_reason TEXT,
    invalid_since BIGINT,
    last_verified_at BIGINT,
    expires_hint_at BIGINT,
    PRIMARY KEY (principal_key)
);

DROP TABLE principal_status;

UPDATE meta SET value = '5' WHERE key = 'schema_version';

UPDATE canvas_mcp_alembic_version SET version_num='0002_accounts' WHERE canvas_mcp_alembic_version.version_num = '0001_baseline_v4';

COMMIT;
