BEGIN;

CREATE TABLE canvas_mcp_alembic_version (
    version_num VARCHAR(32) NOT NULL,
    CONSTRAINT canvas_mcp_alembic_version_pkc PRIMARY KEY (version_num)
);

-- Running upgrade  -> 0001_baseline_v4

CREATE TABLE meta (
    key TEXT NOT NULL,
    value TEXT NOT NULL,
    PRIMARY KEY (key)
);

CREATE TABLE canvas_tokens (
    tenant_id TEXT COLLATE "C" NOT NULL,
    object_id TEXT COLLATE "C" NOT NULL,
    key_id TEXT COLLATE "C" NOT NULL,
    nonce BYTEA NOT NULL,
    ciphertext BYTEA NOT NULL,
    canvas_user_id TEXT NOT NULL,
    canvas_user_name TEXT NOT NULL,
    entra_display_name TEXT DEFAULT '' NOT NULL,
    entra_upn TEXT DEFAULT '' NOT NULL,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    last_used_at BIGINT,
    canvas_host TEXT,
    principal_key TEXT COLLATE "C",
    status TEXT DEFAULT 'active' NOT NULL,
    invalid_reason TEXT,
    invalid_since BIGINT,
    last_verified_at BIGINT,
    expires_hint_at BIGINT,
    PRIMARY KEY (tenant_id, object_id)
);

CREATE UNIQUE INDEX canvas_tokens_principal_key ON canvas_tokens (principal_key);

CREATE TABLE user_tool_prefs (
    principal_key TEXT COLLATE "C" NOT NULL,
    enabled_write_tools TEXT DEFAULT '[]' NOT NULL,
    enabled_at TEXT DEFAULT '{}' NOT NULL,
    updated_at BIGINT NOT NULL,
    updated_via TEXT DEFAULT 'account_web' NOT NULL,
    PRIMARY KEY (principal_key)
);

CREATE TABLE principal_status (
    principal_key TEXT COLLATE "C" NOT NULL,
    status TEXT DEFAULT 'active' NOT NULL,
    disabled_reason TEXT,
    disabled_at BIGINT,
    disabled_by TEXT,
    display_name TEXT DEFAULT '' NOT NULL,
    upn TEXT DEFAULT '' NOT NULL,
    session_epoch BIGINT DEFAULT 0 NOT NULL,
    is_owner BIGINT DEFAULT 0 NOT NULL,
    owner_seen_at BIGINT,
    updated_at BIGINT NOT NULL,
    PRIMARY KEY (principal_key)
);

CREATE TABLE principal_status_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    principal_key TEXT COLLATE "C" NOT NULL,
    action TEXT NOT NULL,
    actor TEXT,
    reason TEXT,
    session_epoch BIGINT NOT NULL,
    at BIGINT NOT NULL,
    PRIMARY KEY (id)
);

CREATE INDEX principal_status_events_principal ON principal_status_events (principal_key, id);

CREATE TABLE credential_generations (
    principal_key TEXT COLLATE "C" NOT NULL,
    generation BIGINT NOT NULL,
    reason TEXT DEFAULT '' NOT NULL,
    updated_at BIGINT NOT NULL,
    PRIMARY KEY (principal_key)
);

INSERT INTO meta (key, value) VALUES ('schema_version', '4');

INSERT INTO canvas_mcp_alembic_version (version_num) VALUES ('0001_baseline_v4') RETURNING canvas_mcp_alembic_version.version_num;

COMMIT;


